Khuzaima Tofeeq 20L-1304 BDS-5A


Importing Necessary Libraries Especially from Scikit-Learn

In [43]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

Defining a class for our machine learning task.
 This class includes functions for


 1: Reading an excel file into a pandas DataFrame.
 2: Splitting our datasets into 80% Training and 20% Testing.
 3: Mapping is done to convert so that the target variable has discrete numeric values like 1,2 for logistic regression.
 4: Data is fitted to the logistic regression model using the training dataset.
 5: Prediction is done based on the test dataset.
 6: Model accuracy are shown through accuracy_score and confusion_matrix.

In [44]:
class TrainingModel():
    def __init__(self,file):
        self.filename=file
        self.df=pd.DataFrame()
        self.iris_train=pd.DataFrame()
        self.iris_test=pd.DataFrame()
        self.logreg=LogisticRegression()

    def Read2DataFrame(self):
        self.df=pd.read_excel(self.filename)
        
        self.df.drop('Unnamed: 0',axis=1,inplace=True)
        column_means = self.df.mean()
        self.df = self.df.fillna(column_means)
        
        
    def Train_Test_Split(self):
        self.iris_train,self.iris_test=train_test_split(self.df,test_size=0.2,random_state=42)
       
    def LogisticModel(self):
        mapping = {
        'Iris-setosa' : 1,
        'Iris-versicolor' : 2,
        'Iris-virginica' : 3
        }

        X_train,y_train = self.iris_train.iloc[:,:-1].values,self.iris_train.iloc[:,[-1]].replace(mapping).values
        X_test,y_test=self.iris_test.iloc[:,:-1].values,self.iris_test.iloc[:,[-1]].replace(mapping).values

        self.logreg.fit(X_train,y_train)
        
        y_pred=self.logreg.predict(X_test)

        print("Accuracy of Logistic Regression Model:", accuracy_score(y_test,y_pred))

        print(confusion_matrix(y_test,y_pred))

The accuracy for our cleaned iris dataset is 83%. Accuracy is low as compared to the original iris dataset as we may have removed features from the iris dataset which had some meaningful and distinct information in predicting the target. Hence the low accuracy.

In [45]:
file='clean_iris.xlsx'
clean_iris=TrainingModel(file)
clean_iris.Read2DataFrame()
clean_iris.Train_Test_Split()
clean_iris.LogisticModel()

sepal depth       0
sepal diameter    0
target            0
dtype: int64
Accuracy of Logistic Regression Model: 0.8333333333333334
[[ 7  3  0]
 [ 1  8  0]
 [ 0  1 10]]


C:\Users\tofee\AppData\Local\Temp\ipykernel_15380\883273786.py:13: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  column_means = self.df.mean()
c:\Users\tofee\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


The accuracy of the original iris dataset is 100%. As this dataset has all the features required for the prediction of target. Moreover, the are also no missing values. Hence the 100% accuracy.

In [46]:
file='Original Iris.xlsx'
original_iris=TrainingModel(file)
original_iris.Read2DataFrame()
original_iris.Train_Test_Split()
original_iris.LogisticModel()

C:\Users\tofee\AppData\Local\Temp\ipykernel_15380\883273786.py:13: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  column_means = self.df.mean()
c:\Users\tofee\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


sepal length    0
sepal width     0
petal length    0
petal width     0
target          0
dtype: int64
Accuracy of Logistic Regression Model: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


The model couldn't train and predict on the my_iris dataset as this dataset has too many missing values in it.

In [47]:
file='my_iris.xlsx'
my_iris=TrainingModel(file)
my_iris.Read2DataFrame()
my_iris.Train_Test_Split()
my_iris.LogisticModel()

C:\Users\tofee\AppData\Local\Temp\ipykernel_15380\883273786.py:13: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  column_means = self.df.mean()


sepal depth       0
sepal diameter    0
petal depth       0
petal diameter    0
sepal length      0
sepal width       0
petal length      0
petal width       0
target            0
dtype: int64
Accuracy of Logistic Regression Model: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


c:\Users\tofee\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\Users\tofee\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
