In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [112]:
df=pd.read_csv('Neural Networks In Action.csv')

In [113]:
df.head()

Neural Networks using Gradient Decent (XNOR Problem) Unnamed: 1  \
0                                                NaN          NaN   
1                                                 i1           i2   
2                                                  0            0   
3                                                  0            1   
4                                                  1            0   

    Unnamed: 2   Unnamed: 3   Unnamed: 4   Unnamed: 5   Unnamed: 6  \
0          NaN          NaN          NaN          NaN          NaN   
1          w11          w12          w21          w22           h1   
2  1.110623657  1.110323739  1.237790479  1.110323739          0.5   
3  1.110623657  1.110323739  1.237790479  1.110323739  0.775179181   
4  1.110623657  1.110323739  1.237790479  1.110323739  0.752245362   

     Unnamed: 7   Unnamed: 8   Unnamed: 9   Unnamed: 10 Unnamed: 11  \
0           NaN          NaN          NaN           NaN         NaN   
1            h2          wh1          wh2             o           t   
2           0.5  1.204296592  1.203003699  0.7691734875           1   
3  0.7521894616  1.204296592  1.203003699  0.8627631988           0   
4  0.7521894616  1.204296592  1.203003699  0.8594601318           0   

     Unnamed: 12    Unnamed: 13    Unnamed: 14  
0            NaN            NaN            NaN  
1             Eo            Eh1            Eh2  
2   0.2308265125   0.1154752414    0.115351271  
3  -0.8627631988  -0.4316132823  -0.4311499165  
4  -0.8594601318  -0.4299608618    -0.42949927

In [114]:
input=np.array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]).T
input


array([[0, 0, 1, 1],
       [0, 1, 0, 1]])

In [115]:
weights=np.ones(shape=(4,4))

In [116]:
weights_h=np.ones(shape=(4,2))

In [117]:
hidden_layer=weights@ input.T
hidden_layer

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [118]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [119]:
hl_sigmoid=sigmoid(hidden_layer)
hl_sigmoid

array([[0.88079708, 0.88079708],
       [0.88079708, 0.88079708],
       [0.88079708, 0.88079708],
       [0.88079708, 0.88079708]])

In [120]:
output=weights_h.T @hl_sigmoid
output

array([[3.52318831, 3.52318831],
       [3.52318831, 3.52318831]])

In [121]:
output_sigmoid=sigmoid(output)
output_sigmoid

array([[0.97134039, 0.97134039],
       [0.97134039, 0.97134039]])

In [122]:
output_sigmoid=output_sigmoid.flatten()
output_sigmoid=np.vstack(output_sigmoid)
output_sigmoid

array([[0.97134039],
       [0.97134039],
       [0.97134039],
       [0.97134039]])

In [123]:
actual_value=[1,0,0,1]
actual_value=np.vstack(actual_value)
actual_value

array([[1],
       [0],
       [0],
       [1]])

In [124]:
Eo=actual_value-output_sigmoid
Eo.shape

(4, 1)

In [125]:
Eh1_w=weights_h[:,0]
Eh1_w=np.vstack(Eh1_w)
Eh1=Eh1_w * Eo
Eh1

array([[ 0.02865961],
       [-0.97134039],
       [-0.97134039],
       [ 0.02865961]])

In [126]:
Eh2_w=weights_h[:,1]
Eh2_w=np.vstack(Eh1_w)
Eh2=Eh2_w * Eo
Eh2


array([[ 0.02865961],
       [-0.97134039],
       [-0.97134039],
       [ 0.02865961]])

In [137]:
Eh=np.c_[Eh1,Eh2]
Eh

array([[ 0.02865961,  0.02865961],
       [-0.97134039, -0.97134039],
       [-0.97134039, -0.97134039],
       [ 0.02865961,  0.02865961]])

In [129]:
h1_s=hl_sigmoid[:,0]
h1_s=np.vstack(h1_s)

delta_wh1=(Eo * output_sigmoid * (1-output_sigmoid)) * h1_s
delta_wh1


array([[ 0.00070273],
       [-0.02381711],
       [-0.02381711],
       [ 0.00070273]])

In [130]:
h2_s=hl_sigmoid[:,1]
h2_s=np.vstack(h2_s)

delta_wh2=(Eo * output_sigmoid * (1-output_sigmoid)) * h2_s
delta_wh2

array([[ 0.00070273],
       [-0.02381711],
       [-0.02381711],
       [ 0.00070273]])

In [136]:
delta_h=np.c_[delta_wh1,delta_wh2]
updated_weights_h= weights_h - (0.5*delta_h)
updated_weights_h

array([[0.99964864, 0.99964864],
       [1.01190855, 1.01190855],
       [1.01190855, 1.01190855],
       [0.99964864, 0.99964864]])

In [158]:

delta_input_weights= (Eh * hl_sigmoid * (1-hl_sigmoid)) * input.T
delta_input_weights=np.sum(np.reshape(delta_input_weights, newshape=(2, 4)), axis=0)

In [159]:
updated_input_weights=weights- (0.5 * delta_input_weights)
updated_input_weights

array([[1.05099226, 1.        , 0.99849546, 1.04948772],
       [1.05099226, 1.        , 0.99849546, 1.04948772],
       [1.05099226, 1.        , 0.99849546, 1.04948772],
       [1.05099226, 1.        , 0.99849546, 1.04948772]])